### PR TITLE
Mithun fertilizer context 2

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
@mithunpaul08, please use this branch rather than the older one of nearly the same name.  Everything except that bad merges has been moved here.  The other can be deleted unless you had pending changes.

**Comment by mithunpaul08** [comment]
ok i have switched working to this new branch.  but there i nothing else left from my side to fix in this branch. merge?

**Comment by kwalcock** [comment]
@mithunpaul08, you might give Mihai a second chance to look at it by adding him as a reviewer.  I don't see that last time he gave a definitive go ahead.  I'm not familiar enough with the program's requirements to know whether they've been satisfied.  This question from earlier remains:

If contexts.nonEmpty but !contexts.contains(i), the tsv version will not print anything. Is that intended?

You wondered once about whether getEntityFreqPerSent was extendible.  It looks like you are up to 4 different tags.  It's soon time to generalize that.

**Comment by kwalcock** [comment]
@mithunpaul08, I'm deleting the other branch then at origin to free up the name for reuse.  You might want to delete your local copy.

**Comment by mithunpaul08** [comment]
@MihaiSurdeanu can you merge this?


@kwalcock 
If contexts.nonEmpty but !contexts.contains(i), the tsv version will not print anything. Is that intended? 
Ans: yes. If there is no context associated with a sentence, nothing will be printed.

You wondered once about whether getEntityFreqPerSent was extendible. It looks like you are up to 4 different tags. It's soon time to generalize that. 
Ans: yes, that is in my todo. once this is merged with main, i will start a new branch and work on it.

**Comment by MihaiSurdeanu** [comment]
This is good. Thanks both!

**Comment by kwalcock** [comment]
@mithunpaul08, if that is the case with the printing, that nothing not even the variableText, valueText, and sentenceText should be printed, then I need to change it in the json version.  Can you confirm.  Thanks.

**Comment by mithunpaul08** [comment]
@kwalcock i have asked mihai. and also started a new branch to fix this- if he says yes.

**Comment by kwalcock** [comment]
I hope not to have imagined some work into existence :-(  Just want to be sure, especially if a misunderstanding means rerunning the program for a week.

**Pull request merged**
