### PR TITLE
will print only jsonl files. no more json

### PR DESCRIPTION
**Pull request by mithunpaul08**
had spoken to Tomek and he said jsonl is enough for him. So I have removed the lines that print json. Though a part of me says more the better? I will let you make that call @MihaiSurdeanu

### CODE REVIEW

**Comment by kwalcock** [comment]
It looks fine (except for the failing test).  I suspect that an additional import can be removed.

**Comment by MihaiSurdeanu** [comment]
I am Ok with JSONL only. But please comment out the failing JSON test.

**Comment by kwalcock** [comment]
If "it" is replaced by "ignore", then the code will continue to compile and be refactored with other changes.  It sometimes works better than commenting things out.

**Comment by kwalcock** [comment]
The tests pass, so I'll merge.

**Pull request merged**
