### PR TITLE
new variable reader tests

### PR DESCRIPTION
**Pull request by maxaalexeeva**

### CODE REVIEW

**Comment by kwalcock** [comment]
Would it be possible for you to grep for
```scala
extends FlatSpec with Matchers
```
and replace it with
```scala
extends Test
```
and any required imports if these nearby files are being changed anyway?  Some of them got away some time ago.  Thank you!

**Comment by maxaalexeeva** [comment]
Closing because there are more current related branches. @kwalcock I think somebody (you?) made the adjustment you requested in another branch.

**Comment by kwalcock** [comment]
I made some adjustments, but I don't see that the ignored test for sent21_12 is in main or the file TestVariableReaderEntities.  Perhaps they are no longer needed.

**Comment by maxaalexeeva** [comment]
@kwalcock yeah @IkeKobby has a different branch going on with all the necessary stuff from here and will open a pr soon

**Pull request closed without merging**
