### PR TITLE
Label/norm tests

### PR DESCRIPTION
**Pull request by maxaalexeeva**
- Started a test set that checks events for labels and norms
- added a couple of rules to make the sample test pass

### CODE REVIEW

**Comment by maxaalexeeva** [comment]
@MihaiSurdeanu, this is based on @kwalcock's restructuring of previously made variable tests---those were checking for variable text and both value text and norm. Right now, the tests  in this file are checking for label and norm, but I have not removed the ability to check for text in case decide we want to do that. Is the sample test what you wanted?

**Comment by maxaalexeeva** [comment]
@IkeKobby, fyi

**Review by kwalcock — APPROVED** [review]
That looks OK to me.  FWIW some of the extra indexes and tuples are there so that the error messages are more informative.  When tests fail it is more difficult than usual to identify a unique condition that is bad, so some extra context is added.

**Comment by maxaalexeeva** [comment]
Thanks @kwalcock! Gonna merge this, so that @IkeKobby has access to this in the morning gmt. @MihaiSurdeanu, we can adjust in the next pr if that's not what you were suggesting.

**Pull request merged**
