### PR TITLE
Update procVer

### PR DESCRIPTION
**Pull request by kwalcock**
Update processors, except that three tests in TestVariableReader are failing

### CODE REVIEW

**Comment by kwalcock** [comment]
The failing tests are all in TestVariableReader:
```
[info] - should process 21-sent15_4 correctly *** FAILED ***
[info]   ArrayBuffer(org.clulab.odin.EventMention@542523fb, org.clulab.odin.EventMention@3f306914) had size 2 instead of expected size 4 (TestVariableReader.scala:31)

[info] - should process 34-sent16_2_1 correctly *** FAILED ***
[info]   ArrayBuffer() had size 0 instead of expected size 1 (TestVariableReader.scala:31)

[info] - should process 36-sent16_2_3 correctly *** FAILED ***
[info]   ArrayBuffer() had size 0 instead of expected size 1 (TestVariableReader.scala:31)
```

In the first test it misses the commented lines that come from the sentence "The first sowing dates started on July 1st in 2010 and on July 8th in 2011":
```
        ("sowing dates", Seq(("July 1st", "XXXX-07-01"))),
//        ("sowing dates", Seq(("2010", "2010-XX-XX"))),
        ("sowing dates", Seq(("July 8th", "XXXX-07-08"))) //,
//        ("sowing dates", Seq(("2011", "2011-XX-XX")))
```

**Comment by kwalcock** [comment]
The other tests are
```
      "sent16_2_1", "Farmers use cultivar such as sugarcane which are planted on 80 and 20 percent of total area",
      Seq(("cultivar", Seq(("sugarcane", ""))))

      "sent16_2_3", "Farmers preferred to use short duration rice varieties like Sahel 108",
      Seq(("varieties", Seq(("Sahel 108", ""))))
```

**Comment by MihaiSurdeanu** [comment]
@maxaalexeeva: can you please take a look at these? No rush. Thank you!

**Comment by maxaalexeeva** [comment]
@MihaiSurdeanu, updated parser produces a different parse for those sentences. For two sentences, it's an easy rule update. For `sent15_4` (_The first sowing dates started on July 1st in 2010 and on July 8th in 2011_) the parse is really bad, so you can't reach July 8th and 2011. I commented the unreachable dates out for now. 

The changes I made I here: https://github.com/clulab/habitus/pull/121

**Pull request merged**
