### PR TITLE
Produce preserved and restored case

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
Here are the original file and outputs with preserved and restored case that can better be compared to each other, each with one sentence per line.  The main problem was that removeBadSentences returns a new document that needs to have its case restored.  Otherwise case was being restored on the old document that still contained bad sentences.  The saving of the preserved case can be commented out or removed now.

[Bulletin_02_06_2020.en.txt](https://github.com/clulab/habitus/files/8533536/Bulletin_02_06_2020.en.txt)
[Bulletin_02_06_2020.en.txt.preserved.txt](https://github.com/clulab/habitus/files/8533537/Bulletin_02_06_2020.en.txt.preserved.txt)
[Bulletin_02_06_2020.en.txt.restored.txt](https://github.com/clulab/habitus/files/8533538/Bulletin_02_06_2020.en.txt.restored.txt)

FYI @hubert10 @MihaiSurdeanu

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock! This is better, but not quite there. I still see a bunch of sentences with single words, e.g.:

```
prev.
Real.
Prev.
Real.
Prev.
Real.
Prev.
Real.
```

**Comment by kwalcock** [comment]
Indeed!  I forgot the short sentence part.  Should that be added to the isBadSentence method of the HabitusProcessor that applies to documents regardless of whether case is being restored or not?

**Comment by MihaiSurdeanu** [comment]
Yep!

**Comment by kwalcock** [comment]
I also didn't follow instructions on "Sentences that do not contain alpha chars" because there was already a very similar test already in place.  isBadSentence is the place for those details in any case.

[Bulletin_02_06_2020.en.txt.restored.txt](https://github.com/clulab/habitus/files/8535514/Bulletin_02_06_2020.en.txt.restored.txt)
[Bulletin_02_06_2020.en.txt.preserved.txt](https://github.com/clulab/habitus/files/8535515/Bulletin_02_06_2020.en.txt.preserved.txt)

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock ! This is great. Ready to merge.

**Pull request merged**
