### PR TITLE
Mithun testcases saed

### PR DESCRIPTION
**Pull request by mithunpaul08**

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Thanks! I'll take a look at these too.

**Comment by MihaiSurdeanu** [comment]
@kwalcock, this PR fails with a scaliest error I've never seen before. Can you please look into it?

```
org.clulab.habitus.variables.TestVariableReader *** ABORTED ***
[info]   java.lang.NullPointerException:
[info]   at org.scalatest.SuperEngine.getTestNamePrefix(Engine.scala:718)
[info]   at org.scalatest.SuperEngine.getTestName(Engine.scala:722)
[info]   at org.scalatest.SuperEngine.registerTest(Engine.scala:653)
[info]   at org.scalatest.FlatSpecLike.org$scalatest$FlatSpecLike$$registerTestToRun(FlatSpecLike.scala:143)
[info]   at org.scalatest.FlatSpecLike$InAndIgnoreMethods.in(FlatSpecLike.scala:1398)
[info]   at org.clulab.habitus.variables.TestVariableReader.<init>(TestVariableReader.scala:900)
[info]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[info]   ...
```

Meanwhile, I'll make sure the individual tests pass.

**Comment by kwalcock** [comment]
Acknowledged

**Comment by MihaiSurdeanu** [comment]
@mithunpaul08: most of these tests pass, and have been merged in main.
(We are still waiting on some date recognition fixes from processors, but this is usable).

**Pull request merged**
