### PR TITLE
Acronym lexicons

### PR DESCRIPTION
**Pull request by hubert10**
Hi @MihaiSurdeanu,
List of acronyms were added here. Thanks
Hubert

### CODE REVIEW

**Comment by MihaiSurdeanu** [comment]
Thank you @hubert10 !
These are all organizations or projects?

**Comment by hubert10** [comment]
Hi Mihai,
Yes, these are organizations, projects and they also contain things like
currencies such FCFA (Franc of the African Financial Community), do we
really need these?. Let me know if we need to filter them out. I can do it,
I thought we were interested in ORGANIZATIONS or ASSOCIATIONS.
Thanks
Hubert

**Comment by MihaiSurdeanu** [comment]
@hubert10: can you please remove all acronyms that are not animate entities? We should keep just entities we can talk to, i.e., persons, organizations, or projects that are clearly defined (they have a manager).
Thanks!

**Comment by hubert10** [comment]
Hi @MihaiSurdeanu , 
All non animate entities were removed!
Thanks!

**Comment by MihaiSurdeanu** [comment]
Thank you!

**Pull request merged**
