### PR TITLE
yield amount increase

### PR DESCRIPTION
**Pull request by IkeKobby**
- Added rule for extracting yield increase.

### CODE REVIEW

**Review by kwalcock — APPROVED** [review]
It looks fine to me, but probably Mihai and Masha should look as well.

**Comment by kwalcock** [comment]
Thanks for working around that special rule "feature" that was discovered.

**Comment by maxaalexeeva** [comment]
Good on my end.

**Comment by kwalcock** [comment]
Mihai may be busy for a couple days.  If the button needs to be pressed sooner, just say so.

**Comment by maxaalexeeva** [comment]
@kwalcock thanks! I think this change can wait a bit. It's standalone enough not to cause conflicts with or be important for other things we are working on.

**Comment by maxaalexeeva** [comment]
@kwalcock made a small adjustment.

**Comment by maxaalexeeva** [comment]
Hi @MihaiSurdeanu would you have a look at this branch when you have a moment? Thanks!

**Comment by MihaiSurdeanu** [comment]
@maxaalexeeva, @IkeKobby : in general, this looks good. But the usage of `[]*` and `[]+` in the `yield-increase-event` rule scare me, since they are unbounded. Can you add some upper limit on the number of tokens to be scanned?

**Comment by maxaalexeeva** [comment]
@MihaiSurdeanu @kwalcock so, the tests passed on the third re-run here. Been meaning to ask: is there known non-determinism anywhere in the system (i.e., extractions can differ slightly from run to run)? Or does tests passing/failing inconsistently on different runs mean there are bugs somewhere in habitus? (for example in actions or in how rule s were written)

**Comment by MihaiSurdeanu** [comment]
Good question. @kwalcock : can you please check the logs?

**Comment by kwalcock** [comment]
Extractions shouldn't differ from run to run.  There is an occasional test that checks for performance improvement that can get unlucky and fail, but not around here.  The typical culprit is otherwise use of dictionary keys in a way that assumes a stable ordering but that can differ from run to run.  Each time this PR failed was in

```
[info] - should process 5-sent5 correctly *** FAILED ***
[info]   Vector() had size 0 instead of expected size 1 (TestVariableReaderLabelBased.scala:44)
```

If changes around the test and around the changed code don't look suspicious to anyone, I can try to break this locally and investigate.

**Comment by maxaalexeeva** [comment]
@kwalcock thank you! I am not exactly sure what can be causing it, so if you could have a look, that would be great! Thanks for offering! I will also let you know there is another test that breaks more or less consistently on different runs (not only in this branch):

```
- should process 0-sent1 correctly *** FAILED ***
[info]   ArrayBuffer(org.clulab.odin.EventMention@871ce72b) had size 1 instead of expected size 2 (TestVariableReader.scala:44)
```
Some tests in habitus depend on the order of mentions in the sentence, and I sort mentions by token interval to account for that. I might have missed some places where sorting needs to happen, but I don't think that's the issue here since it's the number of mentions that is off and not the contents.

**Comment by kwalcock** [comment]
Thank you!  The more clues, the better.

**Comment by kwalcock** [comment]
This can either pass or fail locally for me.  So far I haven't been able to get the main branch to fail similarly.  It's probably best to leave this here unmerged until I figure it out.  The number of Mentions being found in the test before filtering changes inexplicably and the correct answer has just disappeared for some reason.  They're not supposed to do that.

**Comment by maxaalexeeva** [comment]
@kwalcock I think this is another occasionally failing test:

```
    VariableTest(
      passingTest,
      "sent35", "the potential rice grain yields were between 8.8 t ha-1 and 9.2 t ha-1 ( i.e. about 1 t ha-1 more than in the 1998WS ) whilst the average of the actual yield increased greatly",
      "YieldIncrease",
      Seq(
        ("Yield", Seq(("1 t ha-1", "1.0 t/ha"))),
      )
    ),
```

**Comment by kwalcock** [comment]
Thanks, @maxaalexeeva.  I spent several hours trying to figure the first one out without much success, so maybe I should try the other two to see if they are easier.  The first one did involve the rule that was acting weird before.  Sometimes its action it is not getting any mention to work with as if the rule hadn't applied or something else had clobbered it.

**Comment by maxaalexeeva** [comment]
@kwalcock does the test 5-sent5 ever fail for you when you run it individually with intellij green arrow? Mine doesn't seem to fail that way, but I don't know what to make of it.

**Comment by maxaalexeeva** [comment]
Hi @kwalcock and @MihaiSurdeanu, I tried adjusting the rules to exclude ranges and then with ranges but no lexical constraints. Here is what I get (still rules failing/passing randomly):

(sent numbers indicate failing sentences; this is only for TestVariableReaderLabelBased run with `sbt testOnly...`)

This is the current state of branch:

1. Sent 5
2. Pass
3. Sent 5
4. Sent 5
5. Sent 5, 7, 35
6. Pass
7. Sent 5
8. Sent 5, 35
9. Pass
10. Sent 7

The next one is without ranges:
Screenshot from 2022-08-25 13-35-14

1. Pass
2. Sent 35
3. Sent 35
4. Sent 35
5. Pass
6. Pass
7. Sent 35
8. Pass
9. Sent 35
10. pass

This is with ranges but no lexicon constraints:
Screenshot from 2022-08-25 13-59-54

1. Pass
2. Sent 5, 35
3. Sent 5
4. Pass
5. Sent 5, 35
6. Sent 35
7. Sent 35
8. Pass
9. Sent 5
10. Pass

I'm not sure what to make of this, tbh.

**Comment by kwalcock** [comment]
I found something similar.  If the rule with action yieldAmountActionFlow is changed from the intervals to + and *, there hasn't been a failure yet.   If I trace the number of mentions entering and leaving any action, the difference between a passing test and a failing test is that the passing one calls yieldAmountActionFlow with a mention in the list and the failing one has none in the list.  So far, I haven't found anything else different.

Passing | Failing
-- | --
WARNING: Entering   default with 1. | WARNING: Entering default with 1.
WARNING: Exiting default with 1. | WARNING: Exiting default with 1.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 1. | WARNING: Entering default with 1.
WARNING: Exiting default with 1. | WARNING: Exiting default with 1.
WARNING: Entering default with 2. | WARNING: Entering default with 2.
WARNING: Exiting default with 2. | WARNING: Exiting default with 2.
WARNING: Entering default with 3. | WARNING: Entering default with 3.
WARNING: Exiting default with 3. | WARNING: Exiting default with 3.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 1. | WARNING: Entering default with 1.
WARNING: Exiting default with 1. | WARNING: Exiting default with 1.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering mkNumberRangeMention   with 0. | WARNING: Entering mkNumberRangeMention with 0.
WARNING: Exiting mkNumberRangeMention   with 0. | WARNING: Exiting mkNumberRangeMention with 0.
WARNING: Entering mkNumberRangeMention   with 0. | WARNING: Entering mkNumberRangeMention with 0.
WARNING: Exiting mkNumberRangeMention   with 0. | WARNING: Exiting mkNumberRangeMention with 0.
WARNING: Entering mkNumberRangeMention   with 0. | WARNING: Entering mkNumberRangeMention with 0.
WARNING: Exiting mkNumberRangeMention   with 0. | WARNING: Exiting mkNumberRangeMention with 0.
WARNING: Entering mkDateMention with 0. | WARNING: Entering mkDateMention with 0.
WARNING: Exiting mkDateMention with 0. | WARNING: Exiting mkDateMention with 0.
WARNING: Entering mkDateMention with 0. | WARNING: Entering mkDateMention with 0.
WARNING: Exiting mkDateMention with 0. | WARNING: Exiting mkDateMention with 0.
WARNING: Entering mkDateMention with 0. | WARNING: Entering mkDateMention with 0.
WARNING: Exiting mkDateMention with 0. | WARNING: Exiting mkDateMention with 0.
WARNING: Entering mkDateMention with 0. | WARNING: Entering mkDateMention with 0.
WARNING: Exiting mkDateMention with 0. | WARNING: Exiting mkDateMention with 0.
WARNING: Entering mkDateMention with 0. | WARNING: Entering mkDateMention with 0.
WARNING: Exiting mkDateMention with 0. | WARNING: Exiting mkDateMention with 0.
WARNING: Entering mkDateMention with 0. | WARNING: Entering mkDateMention with 0.
WARNING: Exiting mkDateMention with 0. | WARNING: Exiting mkDateMention with 0.
WARNING: Entering mkDateMention with 2. | WARNING: Entering mkDateMention with 2.
WARNING: Exiting mkDateMention with 2. | WARNING: Exiting mkDateMention with 2.
WARNING: Entering mkDateMention with 0. | WARNING: Entering mkDateMention with 0.
WARNING: Exiting mkDateMention with 0. | WARNING: Exiting mkDateMention with 0.
WARNING: Entering mkDateMentionYyyyMmDd   with 0. | WARNING: Entering mkDateMentionYyyyMmDd with 0.
WARNING: Exiting mkDateMentionYyyyMmDd   with 0. | WARNING: Exiting mkDateMentionYyyyMmDd with 0.
WARNING: Entering mkDateMentionDdMmYyyy   with 0. | WARNING: Entering mkDateMentionDdMmYyyy with 0.
WARNING: Exiting mkDateMentionDdMmYyyy   with 0. | WARNING: Exiting mkDateMentionDdMmYyyy with 0.
WARNING: Entering mkDateMentionYyMmDd   with 0. | WARNING: Entering mkDateMentionYyMmDd with 0.
WARNING: Exiting mkDateMentionYyMmDd with   0. | WARNING: Exiting mkDateMentionYyMmDd with 0.
WARNING: Entering mkDateMentionYyMm with   0. | WARNING: Entering mkDateMentionYyMm with 0.
WARNING: Exiting mkDateMentionYyMm with   0. | WARNING: Exiting mkDateMentionYyMm with 0.
WARNING: Entering mkDateMentionMmYyyy   with 0. | WARNING: Entering mkDateMentionMmYyyy with 0.
WARNING: Exiting mkDateMentionMmYyyy with   0. | WARNING: Exiting mkDateMentionMmYyyy with 0.
WARNING: Entering mkDateMentionYyyyMm   with 0. | WARNING: Entering mkDateMentionYyyyMm with 0.
WARNING: Exiting mkDateMentionYyyyMm with   0. | WARNING: Exiting mkDateMentionYyyyMm with 0.
WARNING: Entering mkDateMention with 0. | WARNING: Entering mkDateMention with 0.
WARNING: Exiting mkDateMention with 0. | WARNING: Exiting mkDateMention with 0.
WARNING: Entering mkDateMentionHoliday   with 0. | WARNING: Entering mkDateMentionHoliday with 0.
WARNING: Exiting mkDateMentionHoliday   with 0. | WARNING: Exiting mkDateMentionHoliday with 0.
WARNING: Entering   mkDateMentionWithModifierApprox with 0. | WARNING: Entering mkDateMentionWithModifierApprox with 0.
WARNING: Exiting   mkDateMentionWithModifierApprox with 0. | WARNING: Exiting mkDateMentionWithModifierApprox with 0.
WARNING: Entering   mkDateMentionWithModifierStart with 0. | WARNING: Entering mkDateMentionWithModifierStart with 0.
WARNING: Exiting   mkDateMentionWithModifierStart with 0. | WARNING: Exiting mkDateMentionWithModifierStart with 0.
WARNING: Entering   mkDateMentionWithModifierMid with 0. | WARNING: Entering mkDateMentionWithModifierMid with 0.
WARNING: Exiting   mkDateMentionWithModifierMid with 0. | WARNING: Exiting mkDateMentionWithModifierMid with 0.
WARNING: Entering   mkDateMentionWithModifierEnd with 0. | WARNING: Entering mkDateMentionWithModifierEnd with 0.
WARNING: Exiting   mkDateMentionWithModifierEnd with 0. | WARNING: Exiting mkDateMentionWithModifierEnd with 0.
WARNING: Entering mkDateRangeMention with   0. | WARNING: Entering mkDateRangeMention with 0.
WARNING: Exiting mkDateRangeMention with   0. | WARNING: Exiting mkDateRangeMention with 0.
WARNING: Entering mkDateRangeMention with   0. | WARNING: Entering mkDateRangeMention with 0.
WARNING: Exiting mkDateRangeMention with   0. | WARNING: Exiting mkDateRangeMention with 0.
WARNING: Entering mkDateRangeMention with   1. | WARNING: Entering mkDateRangeMention with 1.
WARNING: Exiting mkDateRangeMention with   1. | WARNING: Exiting mkDateRangeMention with 1.
WARNING: Entering   mkDateRangeMentionWithNumber with 0. | WARNING: Entering mkDateRangeMentionWithNumber with 0.
WARNING: Exiting   mkDateRangeMentionWithNumber with 0. | WARNING: Exiting mkDateRangeMentionWithNumber with 0.
WARNING: Entering   mkDateRangeMentionWithNumber with 0. | WARNING: Entering mkDateRangeMentionWithNumber with 0.
WARNING: Exiting   mkDateRangeMentionWithNumber with 0. | WARNING: Exiting mkDateRangeMentionWithNumber with 0.
WARNING: Entering   mkDateRangeMentionWithMonth with 0. | WARNING: Entering mkDateRangeMentionWithMonth with 0.
WARNING: Exiting   mkDateRangeMentionWithMonth with 0. | WARNING: Exiting mkDateRangeMentionWithMonth with 0.
WARNING: Entering   mkDateRangeMentionWithMonth with 0. | WARNING: Entering mkDateRangeMentionWithMonth with 0.
WARNING: Exiting   mkDateRangeMentionWithMonth with 0. | WARNING: Exiting mkDateRangeMentionWithMonth with 0.
WARNING: Entering   mkDateRangeMentionWithSinceRef with 1. | WARNING: Entering mkDateRangeMentionWithSinceRef with 1.
WARNING: Exiting   mkDateRangeMentionWithSinceRef with 1. | WARNING: Exiting mkDateRangeMentionWithSinceRef with 1.
WARNING: Entering   mkDateRangeMentionWithUntilRef with 0. | WARNING: Entering mkDateRangeMentionWithUntilRef with 0.
WARNING: Exiting   mkDateRangeMentionWithUntilRef with 0. | WARNING: Exiting mkDateRangeMentionWithUntilRef with 0.
WARNING: Entering   mkDateUnboundRangeMentionBefore with 0. | WARNING: Entering mkDateUnboundRangeMentionBefore with 0.
WARNING: Exiting   mkDateUnboundRangeMentionBefore with 0. | WARNING: Exiting mkDateUnboundRangeMentionBefore with 0.
WARNING: Entering   mkDateUnboundRangeMentionAfter with 0. | WARNING: Entering mkDateUnboundRangeMentionAfter with 0.
WARNING: Exiting   mkDateUnboundRangeMentionAfter with 0. | WARNING: Exiting mkDateUnboundRangeMentionAfter with 0.
WARNING: Entering   mkDateRangeMentionWithSeason with 0. | WARNING: Entering mkDateRangeMentionWithSeason with 0.
WARNING: Exiting   mkDateRangeMentionWithSeason with 0. | WARNING: Exiting mkDateRangeMentionWithSeason with 0.
WARNING: Entering   mkDateRangeMentionWithSeason with 0. | WARNING: Entering mkDateRangeMentionWithSeason with 0.
WARNING: Exiting   mkDateRangeMentionWithSeason with 0. | WARNING: Exiting mkDateRangeMentionWithSeason with 0.
WARNING: Entering   mkDateRangeMentionWithSeasons with 0. | WARNING: Entering mkDateRangeMentionWithSeasons with 0.
WARNING: Exiting   mkDateRangeMentionWithSeasons with 0. | WARNING: Exiting mkDateRangeMentionWithSeasons with 0.
WARNING: Entering   mkDateRangeMentionWithSeasons with 0. | WARNING: Entering mkDateRangeMentionWithSeasons with 0.
WARNING: Exiting   mkDateRangeMentionWithSeasons with 0. | WARNING: Exiting mkDateRangeMentionWithSeasons with 0.
WARNING: Entering   mkDateRangeMentionWithSeasonSinceRef with 0. | WARNING: Entering mkDateRangeMentionWithSeasonSinceRef with 0.
WARNING: Exiting   mkDateRangeMentionWithSeasonSinceRef with 0. | WARNING: Exiting mkDateRangeMentionWithSeasonSinceRef with 0.
WARNING: Entering   mkDateRangeMentionWithSeasonUntilRef with 0. | WARNING: Entering mkDateRangeMentionWithSeasonUntilRef with 0.
WARNING: Exiting   mkDateRangeMentionWithSeasonUntilRef with 0. | WARNING: Exiting mkDateRangeMentionWithSeasonUntilRef with 0.
WARNING: Entering   mkDateUnboundRangeMentionWithSeasonBefore with 0. | WARNING: Entering mkDateUnboundRangeMentionWithSeasonBefore with 0.
WARNING: Exiting   mkDateUnboundRangeMentionWithSeasonBefore with 0. | WARNING: Exiting mkDateUnboundRangeMentionWithSeasonBefore with 0.
WARNING: Entering   mkDateUnboundRangeMentionWithSeasonAfter with 0. | WARNING: Entering mkDateUnboundRangeMentionWithSeasonAfter with 0.
WARNING: Exiting   mkDateUnboundRangeMentionWithSeasonAfter with 0. | WARNING: Exiting mkDateUnboundRangeMentionWithSeasonAfter with 0.
WARNING: Entering   mkDateRangeMentionVagueSeason with 0. | WARNING: Entering mkDateRangeMentionVagueSeason with 0.
WARNING: Exiting   mkDateRangeMentionVagueSeason with 0. | WARNING: Exiting mkDateRangeMentionVagueSeason with 0.
WARNING: Entering   mkDateRangeMentionOneTokenYearRange with 0. | WARNING: Entering mkDateRangeMentionOneTokenYearRange with 0.
WARNING: Exiting   mkDateRangeMentionOneTokenYearRange with 0. | WARNING: Exiting mkDateRangeMentionOneTokenYearRange with 0.
WARNING: Entering mkMeasurementMention   with 1. | WARNING: Entering mkMeasurementMention with 1.
WARNING: Exiting mkMeasurementMention   with 1. | WARNING: Exiting mkMeasurementMention with 1.
WARNING: Entering   mkMeasurementWithRangeMention with 0. | WARNING: Entering mkMeasurementWithRangeMention with 0.
WARNING: Exiting   mkMeasurementWithRangeMention with 0. | WARNING: Exiting mkMeasurementWithRangeMention with 0.
WARNING: Entering   mkSharedMeasurementMention with 0. | WARNING: Entering mkSharedMeasurementMention with 0.
WARNING: Exiting   mkSharedMeasurementMention with 0. | WARNING: Exiting mkSharedMeasurementMention with 0.
WARNING: Entering mkPercentage with 0. | WARNING: Entering mkPercentage with 0.
WARNING: Exiting mkPercentage with 0. | WARNING: Exiting mkPercentage with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 11. | WARNING: Entering default with 11.
WARNING: Exiting default with 11. | WARNING: Exiting default with 11.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 1. | WARNING: Entering default with 1.
WARNING: Exiting default with 1. | WARNING: Exiting default with 1.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 1. | WARNING: Entering default with 1.
WARNING: Exiting default with 1. | WARNING: Exiting default with 1.
WARNING: Entering default with 1. | WARNING: Entering default with 1.
WARNING: Exiting default with 1. | WARNING: Exiting default with 1.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering appropriateMeasurement   with 1. | WARNING: Entering appropriateMeasurement with 1.
WARNING: Exiting appropriateMeasurement   with 1. | WARNING: Exiting appropriateMeasurement with 1.
WARNING: Entering adjustQuantityNorm with   0. | WARNING: Entering adjustQuantityNorm with 0.
WARNING: Exiting adjustQuantityNorm with   0. | WARNING: Exiting adjustQuantityNorm with 0.
WARNING: Entering appropriateMeasurement   with 1. | WARNING: Entering appropriateMeasurement with 1.
t/ha results in false! | t/ha results in false!
WARNING: Exiting appropriateMeasurement   with 1. | WARNING: Exiting appropriateMeasurement with 1.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 1. | WARNING: Entering default with 1.
WARNING: Exiting default with 1. | WARNING: Exiting default with 1.
WARNING: Entering default with 1. | WARNING: Entering default with 1.
WARNING: Exiting default with 1. | WARNING: Exiting default with 1.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering splitIntoBinary with 0. | WARNING: Entering splitIntoBinary with 0.
WARNING: Exiting splitIntoBinary with 0. | WARNING: Exiting splitIntoBinary with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering splitIntoBinary with 0. | WARNING: Entering splitIntoBinary with 0.
WARNING: Exiting splitIntoBinary with 0. | WARNING: Exiting splitIntoBinary with 0.
WARNING: Entering areaVarActionFlow with   0. | WARNING: Entering areaVarActionFlow with 0.
WARNING: Exiting areaVarActionFlow with   0. | WARNING: Exiting areaVarActionFlow with 0.
WARNING: Entering areaVarActionFlow with   0. | WARNING: Entering areaVarActionFlow with 0.
WARNING: Exiting areaVarActionFlow with   0. | WARNING: Exiting areaVarActionFlow with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering splitIntoBinary with 0. | WARNING: Entering splitIntoBinary with 0.
WARNING: Exiting splitIntoBinary with 0. | WARNING: Exiting splitIntoBinary with 0.
WARNING: Entering splitIntoBinary with 0. | WARNING: Entering splitIntoBinary with 0.
WARNING: Exiting splitIntoBinary with 0. | WARNING: Exiting splitIntoBinary with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering   fertilizerEventToRelation with 0. | WARNING: Entering fertilizerEventToRelation with 0.
WARNING: Exiting   fertilizerEventToRelation with 0. | WARNING: Exiting fertilizerEventToRelation with 0.
WARNING: Entering yieldAmountActionFlow   with 1. | WARNING: Entering yieldAmountActionFlow with 0.
  | This shouldn't happen!
WARNING: Exiting yieldAmountActionFlow   with 1. | WARNING: Exiting yieldAmountActionFlow with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 1. | WARNING: Entering default with 1.
WARNING: Exiting default with 1. | WARNING: Exiting default with 1.
WARNING: Entering   fertilizerQuantityActionFlow with 0. | WARNING: Entering fertilizerQuantityActionFlow with 0.
WARNING: Exiting   fertilizerQuantityActionFlow with 0. | WARNING: Exiting fertilizerQuantityActionFlow with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering makeEventFromSplitUnit   with 0. | WARNING: Entering makeEventFromSplitUnit with 0.
WARNING: Exiting makeEventFromSplitUnit   with 0. | WARNING: Exiting makeEventFromSplitUnit with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering splitIntoBinary with 0. | WARNING: Entering splitIntoBinary with 0.
WARNING: Exiting splitIntoBinary with 0. | WARNING: Exiting splitIntoBinary with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering splitIntoBinary with 0. | WARNING: Entering splitIntoBinary with 0.
WARNING: Exiting splitIntoBinary with 0. | WARNING: Exiting splitIntoBinary with 0.
WARNING: Entering areaVarActionFlow with   0. | WARNING: Entering areaVarActionFlow with 0.
WARNING: Exiting areaVarActionFlow with   0. | WARNING: Exiting areaVarActionFlow with 0.
WARNING: Entering areaVarActionFlow with   0. | WARNING: Entering areaVarActionFlow with 0.
WARNING: Exiting areaVarActionFlow with   0. | WARNING: Exiting areaVarActionFlow with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering splitIntoBinary with 0. | WARNING: Entering splitIntoBinary with 0.
WARNING: Exiting splitIntoBinary with 0. | WARNING: Exiting splitIntoBinary with 0.
WARNING: Entering splitIntoBinary with 0. | WARNING: Entering splitIntoBinary with 0.
WARNING: Exiting splitIntoBinary with 0. | WARNING: Exiting splitIntoBinary with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering   fertilizerEventToRelation with 0. | WARNING: Entering fertilizerEventToRelation with 0.
WARNING: Exiting   fertilizerEventToRelation with 0. | WARNING: Exiting fertilizerEventToRelation with 0.
WARNING: Entering yieldAmountActionFlow   with 1. | WARNING: Entering yieldAmountActionFlow with 0.
  | This shouldn't happen!
WARNING: Exiting yieldAmountActionFlow   with 1. | WARNING: Exiting yieldAmountActionFlow with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 1. | WARNING: Entering default with 1.
WARNING: Exiting default with 1. | WARNING: Exiting default with 1.
WARNING: Entering   fertilizerQuantityActionFlow with 0. | WARNING: Entering fertilizerQuantityActionFlow with 0.
WARNING: Exiting   fertilizerQuantityActionFlow with 0. | WARNING: Exiting fertilizerQuantityActionFlow with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering default with 0. | WARNING: Entering default with 0.
WARNING: Exiting default with 0. | WARNING: Exiting default with 0.
WARNING: Entering makeEventFromSplitUnit   with 0. | WARNING: Entering makeEventFromSplitUnit with 0.
WARNING: Exiting makeEventFromSplitUnit   with 0. | WARNING: Exiting makeEventFromSplitUnit with 0.

**Pull request merged**
