### PR TITLE
Remove sentences with too many single-character words

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
I checked tika and scienceparse and they both want to generate lots of single-letter words for FCR_SRVRice.pdf.  In this case, the Adobe converter seems to do significantly better.  One can compare the files below.  I added to the bad sentence check in habitus, but I suppose that the PDF preprocessor could have done this check as well.

[FCR_SRVRice.scienceparse.txt](https://github.com/clulab/habitus/files/8857236/FCR_SRVRice.scienceparse.txt)
[FCR_SRVRice.adobe.txt](https://github.com/clulab/habitus/files/8857237/FCR_SRVRice.adobe.txt)

**Comment by kwalcock** [comment]
I shouldn't merge my own code without more eyes looking at it first, so @IkeKobby, is this a reasonable way to deal with those strange strings of characters?  It's unfortunate that the rest of the sentence gets sacrificed.

**Comment by IkeKobby** [comment]
Hi @kwalcock , in `[FCR_SRVRice.scienceparse.txt](https://github.com/clulab/habitus/files/8857236/FCR_SRVRice.scienceparse.txt)` there are still some sentence with the spaced-out characters. 

But `[FCR_SRVRice.adobe.txt](https://github.com/clulab/habitus/files/8857237/FCR_SRVRice.adobe.txt)` looks good.

**Comment by kwalcock** [comment]
@IkeKobby, the sentences will still be in the txt file, but they will not be processed by habitus.  They will be skipped like the too long and too short sentences.

**Pull request merged**
