### PR TITLE
Evaluate case

### PR DESCRIPTION
**Pull request by kwalcock**

### CODE REVIEW

**Comment by kwalcock** [comment]
One of the Apps in here produces output like that below.  The full document is attached.

| Sentence# | Stage | WordCount | NonWordCount | InitialUpper | AllUpper | AllLower | %NotAllLower | Improved | Text...................................................................................................................................................................................................................................................... |
| --: | --- | --: | --: | --: | --: | --: | --: | --- | --- |
| 0 | preserved | 85 | 13 | 19 | 7 | 46 | 45.9% | - | "JICA Announcement Coalition for the Development of Rice in Africa ( CARD in English ) The CARD initiative ( Coalition for the development of rice growing in Africa ) , jointly proposed by Alliance for a Green Revolution in Africa ( AGRA ) and the Japan International Cooperation Agency ( JICA ) , launched during TICAD IV in May 2008 , today reflects the consensual nature of bilateral and multilateral partners to work together to better meet the needs of African countries rice producers ." |
| 0 | restored | 85 | 13 | 16 | 2 | 54 | 36.5% | ? | "JICA announcement Coalition for the development of Rice in Africa ( card in English ) the card initiative ( Coalition for the development of rice growing in Africa ) , jointly proposed by Alliance for a green revolution in Africa ( Agra ) and the Japan International Cooperation Agency ( JICA ) , launched during Ticad iv in May 2008 , today reflects the consensual nature of bilateral and multilateral partners to work together to better meet the needs of African countries rice producers ." |

The thing to do is to decide if it was a good idea to change from the preserved case to the restored case or not (top line vs. bottom line).  The ? might be replaced by Y or N.  Then we can see if the Y correlates well with higher values of %NotAllLower and figure out where the cutoff should be.  We unfortunately do not see here how the case would affect the parse or reading.  I guess we're going by whether it looks more correct to a human for now.

"Apply case restoration only when it’s needed! Only when T% of words in a sentence are not lower case (i.e., they are numbers, UI, UA)"

[mix.txt.evaluated.txt](https://github.com/clulab/habitus/files/8626833/mix.txt.evaluated.txt)

**Comment by MihaiSurdeanu** [comment]
The sentence in the example should not be restored. This suggests that T >= 50%?

**Comment by kwalcock** [comment]
I moved the output file to Google Drive (https://drive.google.com/file/d/1XYomqowYFy8nAFmvU7uz98LvA-cgNV0_/view?usp=sharing) and am going through sentence by sentence.  Others are welcome to weigh in.  Let me know if the permissions need to change.  They are just for UA now.

**Comment by kwalcock** [comment]
The magic number seems to be 67.5% where precision, recall, and f-score are all 89%.  It's in the spreadsheet.  I don't know at all if having one number per sentence is adequate.  In many sentences, some words are improved and others degraded by "correcting" case.

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock !
Given how mixed the sentences in the txt file are, I suspect checking each individual sentence is the way to go.
Can you please regenerate the "restored" files under this heuristic, and send them to @hubert10 for NER?

**Comment by kwalcock** [comment]
This is continued with #128.  I'm not sure what restored files plural are.  I have Planting dates-20220120T205857Z-001 and SAED-Bulletins-PDF-20220120T205900Z-001.  For now I'm regenerating the sentences that were used to calculate the cutoff first.  @hubert10, what files do you need?

In general, these tables seem to be a big pain.  I haven't had any luck convincing the world to stop using PDFs for conveying information that must be machine read.  How many documents are we talking about?  Is it a small enough number that a human being can remove the tables?  It wouldn't be 100% automated, but it seems like collecting the documents might not be, either.

**Comment by hubert10** [comment]
Hi Keith, I think what I need is the updated code for case restoration so
that I can rerun it on the SAED input txt files I got from Shang-Tai, in
any case I am forwarding them to you. Thanks!

--Hubert

**Pull request merged**
